keywords:
  - "VIE"
  - "V.I.E"
  - "Volontariat international"
  - "Voluntary International Experience" 
notify:
  telegram:
    enabled: false

  email:
    enabled: true
    smtp_host: smtp.gmail.com
    smtp_port: 587
    from_env: SMTP_FROM
    to_env: SMTP_TO
    user_env: SMTP_USER
    pass_env: SMTP_PASS

sites:

  - name: Install Playwright browsers
    uses: microsoft/playwright-github-action@v1

  - name: "Sanofi (VIE)"
    type: "sanofi_vie"
    base: "https://jobs.sanofi.com"
    url:  "https://jobs.sanofi.com/fr/search-jobs/results"
    pre_filtered: true 
    params:
      ActiveFacetID: "VIE"
      CurrentPage: 1
      RecordsPerPage: 50         
      TotalContentResults: ""
      Distance: 50
      RadiusUnitType: 0
      Keywords: ""
      Location: ""
      ShowRadius: "False"
      IsPagination: "False"
      CustomFacetName: ""
      FacetTerm: ""
      FacetType: 0
      "FacetFilters[0].ID": "VIE"
      "FacetFilters[0].FacetType": 5
      "FacetFilters[0].Count": 0
      "FacetFilters[0].Display": "VIE"
      "FacetFilters[0].IsApplied": "true"
      "FacetFilters[0].FieldName": "job_type"
      SearchResultsModuleName: "Search Results"
      SearchFiltersModuleName: "Search Filters"
      SortCriteria: 0
      SortDirection: 0
      SearchType: 5
      PostalCode: ""
      ResultsType: 0

  - name: "Valeo (VIE)"
    type: "workday_raw"
    base_url: "https://valeo.wd3.myworkdayjobs.com/wday/cxs/valeo/valeo_jobs/jobs"
    source: "valeo"
    pre_filtered: true 
    body:
      appliedFacets:
        workerSubType:
          - "1bc7ee912dc9100bd4a826d6e65d0000"   
      limit: 20
      offset: 0
      searchText: ""
  
  - name: "Air Liquide (VIE)"
    type: "workday_raw"
    source: "airliquide"
    base_url: "https://airliquidehr.wd3.myworkdayjobs.com/wday/cxs/airliquidehr/AirLiquideExternalCareer/jobs"
    pre_filtered: true 
    body:
      appliedFacets:
        workerSubType:
          - "431d4efb2c9c01661367fc92f200cd43"   
      limit: 20
      offset: 0
      searchText: ""

  - name: "ArcelorMittal (VIE)"
    type: "oracle_orc"
    source: "arcelormittal"
    base_url: "https://emfg.fa.em4.oraclecloud.com/hcmRestApi/resources/latest/recruitingCEJobRequisitions"
    params:
      onlyData: "true"
      expand: "requisitionList.workLocation,requisitionList.otherWorkLocations,requisitionList.secondaryLocations,flexFieldsFacet.values,requisitionList.requisitionFlexFields"
      finder: "findReqs;siteNumber=CX_4001,facetsList=LOCATIONS;WORK_LOCATIONS;WORKPLACE_TYPES;TITLES;CATEGORIES;ORGANIZATIONS;POSTING_DATES;FLEX_FIELDS,keyword=vie,sortBy=RELEVANCY"
      limit: 50
      offset: 0

  - name: "Air France (VIE)"
    type: "airfrance_talentsoft"
    base: "https://recrutement.airfrance.com"
    url:  "https://recrutement.airfrance.com/pages/offre/listeoffre.aspx?facet_JobDescription_Contract=3445&lcid=2057"
    pre_filtered: true 

  - name: "LVMH (VIE)"
    type: "lvmh"
    url: "https://www.lvmh.com/api/search"
    index: "PRD-fr-fr-timestamp-desc"
    pre_filtered: true 

  - name: "Saint-Gobain (VIE)"
    type: "saint_gobain_playwright"
    base: "https://joinus.saint-gobain.com"
    url:  "https://joinus.saint-gobain.com/fr"
    params:
      "f[0]": "type_contrat:46"    
    max_pages: 8
    pre_filtered: true   
    pre_filtered: true         

                 
